### ISSUE TITLE
ImportError: cannot import name relay

### ISSUE THREAD

**Issue by tou2** [digidotcom/xbee-micropython#14]
I am trying to build and upload "relay frame led" example on pycharm but it gives this error:

ImportError: cannot import name relay

Note: Almost all the other examples are working fine
I am using Xbee3 digimesh pcb antenna.

**Comment by DigiMChh** [comment]
I believe the User Relay frame feature is only available on the XBee3 ZigBee firmware: https://www.digi.com/resources/documentation/Digidocs/90002219/#container/cont_send_receive_user_data.htm

This page was incorrect in stating that it is supported on 802.15.4 and DigiMesh: https://github.com/digidotcom/xbee-micropython/tree/master/samples/xbee/communication/relay_frames_button

**Comment by tomlogic** [comment]
There should be a DigiMesh release later this month that includes support for User Relay frames.

802.15.4 support should be out by the end of September.

**Comment by tou2** [comment]
Thanks, I will test it once its released.
