### ISSUE TITLE
HTTPS JSON problems

### ISSUE THREAD

**Issue by Loynis2018** [digidotcom/xbee-micropython#2]
i can connect with http with json files but when i try to connect with https the micrphyton stop when i write variable.json() and i need reboot the chip. does know someone what happend? actually i am using the urequests library. i have the Xbee cellular

**Comment by tomlogic** [comment]
Can you share the code you're using that works, along with the code that doesn't work?  Does the server you're connecting to support https connections?

**Comment by Loynis2018** [comment]
the code is simple, i have one sever with http and other with https, with http works good, but when i used https the chip blocks itself.

code:
import urequests
a = urequests.get("https:\\pageweb.com\") (i cant show the page beacuse it is firm web test)
i received the 200, how ok, but if i use json block chip.
in explorer https works and show json.

**Comment by tomlogic** [comment]
In your pasted code, you're using a backslash in the URL.  Have you tried `a = urequests.get("https://pageweb.com")`?

**Comment by tomlogic** [comment]
If you want someone to look into this, please re-open this issue and paste the output of a terminal session demonstrating the failure, and hopefully with a URL that we can use to reproduce the failure.
