### ISSUE TITLE
UART not found

### ISSUE THREAD

**Issue by tuorpete** [digidotcom/xbee-micropython#34]
When trying "uart_echo" sample Micropython gives an error "ImportError: cannot import name UART".
I looked into machine-module and it indeed does not have UART in it. 
What seems to be the problem?

**Comment by mikewadsten** [comment]
What model of XBee are you using? Per the Digi MicroPython Programming Guide, only XBee Cellular and XBee 3 Cellular support `machine.UART` at this time: https://www.digi.com/resources/documentation/digidocs/90002219/default.htm#reference/r_features.htm%3FTocPath%3D_____2

**Comment by tuorpete** [comment]
I see. I use the zigbee variant. I did not know what secondary uart meant but it seemed to me like a basic thing that would be available in all devices right from the start :(
