### ISSUE TITLE
Cannot install xbee micropython plugin for pycharm

### ISSUE THREAD

**Issue by iftahgi** [digidotcom/xbee-micropython#50]
![image](https://user-images.githubusercontent.com/7115175/92377160-6125f300-f10c-11ea-921b-763e70282ec9.png)

The xbee micropython plugin cannot be find on pycharm, and when trying to install it from disk, the error message above appears.
I already installed the latest pycharm version. 

Thank you

**Comment by rubenmoral** [comment]
Hi @iftahgi,

Thanks for reporting this issue. We are already working on giving support for PyCharm 2020.2 to the plugin, we expect to release a new version in the next days. We'll let you know when it is available. In the meantime, you can still use the plugin with PyCharm 2020.1 or lower.

Sorry for the inconvenience.

**Comment by iftahgi** [comment]
Many thanks for this prompt reply!

**Comment by rubenmoral** [comment]
Hey @iftahgi, just to let you know that the new version with support for PyCharm 2020.2 is now available.

https://plugins.jetbrains.com/plugin/12445-xbee-micropython

**Comment by iftahgi** [comment]
Thank You!!
